package com.renesistech.quotes.helper

object Constant {

    @JvmField
    val total_tut_screens = 4
    @JvmField
    var headerName = "Content-Type"
    @JvmField
    var headerValue = "application/json"

    @JvmField
    var PACKAGE_NAME: String = "com.igidrive.androidapp"

    var HELPLINE_NUMBER: String = "+924234507777"

    var HOTLINE_NUMBER_ONE: String = "+924234507777"

    var HOTLINE_NUMBER_TWO: String = "+924234507777"

    const val NOTIFICATION_TIME_PERIOD: String = "Year"

    const val ROTATION_DIFF: Float = 20f

    const val DEFAULT_SPEED_LIMIT: Float = 45f

    const val REFERRAL_TOPIC: String = "Lead Generated By Mobile App User For Call Back"

    const val SURVEY_TYPE: String = "SURVEY_TYPE"

    const val REMOVAL_REQUEST: String = "Request for Removal"

    const val ZONE_CROSSING: String = "Request for zone crossing"

    const val BATTERY_TEMPER: String = "Request Pre-Inform Battery Tamper"

    const val UPDATE_REQUEST: String = "Request For Updates"

    const val OTHER_SERVICES: String = "Request for Other Service Requests"

    const val SERVICE_CENTER: String = "service_center"

    const val FIRST_TIME: String = "first_time"

    const val SCREEN_NUM: String = "screen_num"

    const val FAQ_FILE_NAME: String = "faq.pdf"

    const val PRIVACY_FILE_NAME: String = "privacy.pdf"

    const val TERMS_FILE_NAME: String = "tandc.pdf"

    const val PROMOTION_FILE_NAME: String = "promotions.pdf"

    const val INSURANCE_FILE_NAME: String = "insurancepolicy.pdf"

    const val CERTIFICATE_FILE_NAME: String = "certificate.pdf"

    const val YOUTUBE_VIDEO: String = "https://www.youtube.com/watch?v=_qlgEbB_Dk4&list=PLV-vO7y4g57jq4DAogiBE-yM-biAWFvbB"

    const val FAQ_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=faqs.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val PRIVACY_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=privacy.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val TERMS_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=tandc.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val PROMOTION_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=promotions.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val INSURANCE_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=insurancepolicy.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val CERTIFICATE_FILE_PATH: String = "https://igicrm.igiinsurance.com.pk/documentstorageprod/Document/DownloadFile/?fileName=certificate.pdf&entityName=Mobile_App&recordId=3bee6525-fc4a-e911-a96d-000d3a3a0ec3"

    const val MAX_RETRIES: Int = 5

    const val RETRY_DELAY: Int = 5000

    const val CONN_TIMEOUT: Long = 60

    const val READ_TIMEOUT: Long = 40

    const val DIALOG_DELAY: Long = 400

    val SETTING_TYPE_NAMES = listOf("Ignition On/Off", "SVR Night Time Activity", "Excessive idling", "No Go Area", "High Risk Zone")

    val MAINTENANCE_TYPE_NAMES = listOf("Engine Oil Change", "Tire Pressure Check", "Coolant Level Check", "Air Filter Change", "Oil Filter Change", "Transmission Fluid", "Vehicle Tax", "M-Tag Number")
    val MAINTENANCE_TYPE_LIST = listOf("engine_oil", "tire_pressure", "coolant_level", "air_filter", "oil_filter", "transmission_fluid", "vehicle_tax", "mtag_number")

    const val ENGINE_OIL : String = "Engine Oil Change"
    const val ENGINE_OIL_MESSAGE : String = "Time to check your engine oil for "
    const val ENGINE_OIL_TYPE : String = "engine_oil"

    const val TIRE_PRESSURE : String = "Tire Pressure Check"
    const val TIRE_PRESSURE_MESSAGE : String = "Time to check your tire pressure for "
    const val TIRE_PRESSURE_TYPE : String = "tire_pressure"

    const val COOLANT_LEVEL : String = "Coolant Level Check"
    const val COOLANT_LEVEL_MESSAGE : String = "Time to check your coolant level for "
    const val COOLANT_LEVEL_TYPE : String = "coolant_level"

    const val AIR_FILTER : String = "Air Filter Change"
    const val AIR_FILTER_MESSAGE : String = "Time to check your air filter for "
    const val AIR_FILTER_TYPE : String = "air_filter"

    const val OIL_FILTER : String = "Oil Filter Change"
    const val OIL_FILTER_MESSAGE : String = "Time to check your oil filter for "
    const val OIL_FILTER_TYPE : String = "oil_filter"

    const val TRANSMISSION_FLUID : String = "Transmission Fluid"
    const val TRANSMISSION_FLUID_MESSAGE : String = "Time to check your transmission fluid for "
    const val TRANSMISSION_FLUID_TYPE : String = "transmission_fluid"

    const val VEHICLE_TAX : String = "Vehicle Tax"
    const val VEHICLE_TAX_MESSAGE : String = "Time to check your vehicle Tax "
    const val VEHICLE_TAX_TYPE : String = "vehicle_tax"

    const val MTAG_NUMBER : String = "M-Tag Number"
    const val MTAG_NUMBER_MESSAGE : String = "Time to check your M-Tag Number "
    const val MTAG_NUMBER_TYPE : String = "mtag_number"

    const val ODOMETER_READING : String = "Odometer Reading"
    const val ODOMETER_READING_TYPE : String = "odometer_reading"

    const val NONE : String = "--"

    const val NO_CONNECTIVITY : String = "no_conn"

    const val HELPLINE : String = "helpline"
    const val HOTLINE1 : String = "hotline1"
    const val HOTLINE2 : String = "hotline2"



}
